web:
  build: .
  command: bundle exec foreman start
  volumes:
    - .:/home/user
    - worldcup_bundle:/bundle
    - worldcup_node_modules:/var/app/node_modules
    - worldcup_bower:/var/app/vendor/assets/components
  ports:
    - "5000:5000"
    - "5001:5001"
  links:
    - db
    - redis
    - elasticsearch
    - kibana
  environment:
    - RACK_ENV=development
    - RAILS_ENV=development
    - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    - REDIS_URL=redis://redis:6379
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - SECRET_KEY_BASE=f6fd9d146ebd626120771b1b149b194b2aeadd1d04ac3ede151d8682ab1b9142f4659324193c350c51d0f0a11f69570f851fa489d21e3ded15ab79f3b535f9cb
db:
  image: postgres:latest
  volumes:
    - worldcup_db:/var/lib/postgresql/data
  environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
redis:
  image: redis:3.2.9-alpine
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
  environment:
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  volumes:
    - elasticsearch:/usr/share/elasticsearch/data
kibana:
  image: docker.elastic.co/kibana/kibana-oss:6.2.4
  links:
    - elasticsearch
  ports:
    - "5602:5602"
ngrok:
  image: wernight/ngrok
  links:
    - web
  command: ngrok http web:5000
  ports:
    - "4040:4040"
adminer:
  image: adminer
  links:
    - db
    - elasticsearch
  ports:
    - "8080:8080"
